class Account {
  int id;
  String fullname;
  String? image;
  String? email;
  String phone;
  String address;
  // String password;
  // Autogenerated(
  //     {this.id,
  //     this.name,
  //     this.email,
  //     this.emailVerifiedAt,
  //     this.createdAt,
  //     this.updatedAt});
  Account.fromJson(Map<String, dynamic> json)
      : id = json['id'],
        fullname = json['fullname'],
        image = json['image'],
        email = json['email'],
        phone = json['phone'],
        address = json['address'];
  // password = json['password'];

  // Map<String, dynamic> toJson() => {'id': id, 'name': name, 'email': email};
}
